//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using System.Web;
namespace NewFlucompMVC.App_Data
{
}

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("Content", Namespace = "", IsNullable = false)]
public partial class Content
{

	private object[] itemsField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Global", typeof(ContentGlobal), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlElementAttribute("Page", typeof(ContentPage), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public object[] Items
	{
		get
		{
			return this.itemsField;
		}
		set
		{
			this.itemsField = value;
		}
	}
	[XmlIgnore]
	public ContentGlobal Global
	{
		get { return this.itemsField[0] as ContentGlobal; }
	}
	private Dictionary<string, ContentPage> _pages;
	[XmlIgnore]
	public Dictionary<string, ContentPage> Pages
	{
		get
		{
			if (_pages == null)
			{
				_pages = new Dictionary<string, ContentPage>();
				for (int i = 1; i < this.itemsField.Length; i++)
				{
					var pg = this.itemsField[i] as ContentPage;
					_pages[pg.Name] = pg;
				}
			}
			return _pages;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ContentGlobal
{

	private string fullCompanyNameField;

	private string companyDescriptionField;

	private string sEOKeywordsField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string FullCompanyName
	{
		get
		{
			return this.fullCompanyNameField;
		}
		set
		{
			this.fullCompanyNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string CompanyDescription
	{
		get
		{
			return this.companyDescriptionField;
		}
		set
		{
			this.companyDescriptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string SEOKeywords
	{
		get
		{
			return this.sEOKeywordsField;
		}
		set
		{
			this.sEOKeywordsField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ContentPage
{

	private ContentPagePerson[] personField;

	private ContentPageProduct[] productField;

	private ContentPageContent[] contentField;

	private string nameField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Person", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public ContentPagePerson[] Person
	{
		get
		{
			return this.personField;
		}
		set
		{
			this.personField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Product", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public ContentPageProduct[] Product
	{
		get
		{
			return this.productField;
		}
		set
		{
			this.productField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Content", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
	public ContentPageContent[] Content
	{
		get
		{
			return this.contentField;
		}
		set
		{
			this.contentField = value;
		}
	}
	private Dictionary<string, ContentPageContent> _cont;
	[XmlIgnore]
	public Dictionary<string, ContentPageContent> Contents
	{
		get
		{
			if (_cont == null)
			{
				_cont = new Dictionary<string, ContentPageContent>();
				foreach (var cont in Content)
				{
					_cont[cont.Name] = cont;
				}
			}
			return _cont;
		}
	}
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ContentPagePerson
{

	private string nameField;

	private string experienceField;

	private string positionField;

	private string biographyField;

	private string pictureField;
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Picture
	{
		get { return this.pictureField; }
		set { this.pictureField = value; }
	}
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Experience
	{
		get
		{
			return this.experienceField;
		}
		set
		{
			this.experienceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Position
	{
		get
		{
			return this.positionField;
		}
		set
		{
			this.positionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Biography
	{
		get
		{
			return this.biographyField;
		}
		set
		{
			this.biographyField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ContentPageProduct
{

	private string nameField;

	private string descriptionField;
	private string linkField;
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Link
	{
		get
		{
			return this.linkField;
		}
		set
		{
			this.linkField = value;
		}
	}
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ContentPageContent
{

	private string nameField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}
	[XmlIgnore]
	public HtmlString HtmlValue
	{
		get
		{
			return new HtmlString(this.valueField);
		}
	}
	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}
